stages:
  - publish

pages:
  image: ruby:2.6-alpine3.9
  cache:
    key: jekyll
    paths:
      - .bundle_cache/
  before_script:
    - apk update
    - apk add --no-cache build-base curl
    - bundle install --path .bundle_cache/
  script:
    - JEKYLL_ENV=production bundle exec jekyll build -d public
    - curl -o public/danh.pdf https://gitlab.com/zdtcd/resume/uploads/9bf36106ef0adabe1f245efa820d9368/resume.pdf
  artifacts:
    paths:
      - public
  stage: publish
  only:
    - master
