stages:
  - publish

pages:
  image: ruby:2.6-alpine3.9
  cache:
    key: jekyll
    paths:
      - .bundle_cache/
  before_script:
    - apk update
    - apk add --no-cache build-base git
    - bundle install --path .bundle_cache/
  script:
    - JEKYLL_ENV=production bundle exec jekyll build -d public
    - git cat-file blob resume.pdf >| public/danh.pdf
  artifacts:
    paths:
      - public
  stage: publish
  only:
    - master
