stages:
  - publish

pages:
  image: ruby:2.4-alpine3.6
  cache:
    key: jekyll
    paths:
      - .bundle_cache/
  before_script:
    - apk update
    - apk add build-base
    - bundle install --path .bundle_cache/
  script:
    - JEKYLL_ENV=production bundle exec jekyll build -d public
  artifacts:
    paths:
      - public
  stage: publish
  only:
    - master
