# Site settings
title: "(blog 'danh)"
description: "My name is Danh"
url: "https://danh.dev"
author:
  name: "Danh DOAN"
  email: "congdanhqx@gmail.com"
  url: "https://danh.dev"

# Build settings
baseurl: /
github: https://github.com/sgn
gitlab: https://gitlab.com/sgn
markdown: kramdown
source: .
destination: ./_site
permalink: /:year-:month-:day-:title.html
paginate: 8
paginate_path: /page:num/
plugins:
  - jekyll-paginate
  - jekyll-assets
exclude: [syntax-extractor, org, vendor, resume]

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
