# Site settings
title: "(blog 'sgn-danh)"
description: "My name is Danh"
url: "https://congdanhqx.gitlab.io"
author:
  name: "Danh DOAN"
  email: "sgn.danh@gmail.com"
  url: "https://congdanhqx.gitlab.io"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
github: https://github.com/congdanhqx
gitlab: https://gitlab.com/congdanhqx
markdown: kramdown
source: .
destination: ./_site
permalink: /:title.html
paginate: 8
paginate_path: /page:num/
gems:
  - jekyll-paginate
  - jekyll-assets
exclude: [syntax-extractor, org, vendor]

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
