.TH danh 7 2018-12-18 "Ho Chi Minh, Vietnam" "Danh Doan"
.SH NAME
danh \- software developer
.SH SYNOPSIS
.B danh
.B --help
.I question
.SH CONTACT
Email: congdanhqx@gmail.com
.br
PGP Key: 7D953879560F17C2
.br
PGP key fingerprint: 85F0 E2BD 30F2 2A9E E94A  4092 7D95 3879 560F 17C2
.SH NOTE
.PP
This document is best viewed by running
.B man\ <(curl\ -s\ \%https://danh.dev/danh.7)
in your terminal.
.SH DESCRIPTION
.PP
.B danh
is a software engineer with high fluency in
.I C
and
.I C++
.PP
He uses
.B git(1)
to manage his source code at work, and his personal stuff.
.PP
He is a proficient Linux user, beginning with Fedora, CentOS, Arch Linux,
and settled on Void Linux.
.SH WORK EXPERIENCE
.SS Luxoft Vietnam (November\ 2015\(enpresent)
.TP
.I Aug\ 2018\(enpresent:
Being contractor for Continental GmbH. to develop HMI model/view
for cars built by a Korean corporation.

Written in C++, XML, and run on OSEK.

Source code was tracked by
.B git(1)
.TP
.I Jan\ 2018\(enAug\ 2018
Relocated back to Luxoft Vietnam to continue below project.
.TP
.I April\ 2017\(enDec\ 2017
Relocated to Informa Solutions, Singapore.

Contracted by Continental GmbH. to maintain the C++ widget and animation
foundation class to build HMI layer for cars built by a Germany corporation.

Also, wrote automation script for testing and Jenkins build reporting.

Project was write in C++, XML, and run on OSEK.

Source code was tracked by
.B git(1)
.TP
.I April\ 2016\(enMarch\ 2017
Mentored new hire, who had just graduated from university.

Help them get familiar with software process, bug report process,
and source version control system
.B git(1)
.TP
.I Nov\ 2015\(enMar\ 2016:
Joined in last phase of development for HMI of infortainment system
for car built by a Korean corporation.

Project was outsourced from Harman-Becker.

Written by C++, xml, and run on QNX.

Source code was tracked by perforce
.B p4(1)
.SS FPT Software (Nov\ 2013\(enOct\ 2015)
Contracted by DirecTV, US to develop video processing system.

Said system process RTP stream into segmented (DASH/HLS) video stream.

Said system also managed Digital Right Management (DRM).

Written in C++11, boost, run on RHEL

Source code was tracked by subversion
.B svn(1)
.SH EDUCATION
.SS FPT University, Vietnam
Graduated as good student in
.I Software Engineer
on
.I Sept\ 2013
.SH BUGS
.PP
He is a minimalist.
.SH SEE ALSO
.I \%https://danh.dev
